# Generated by Django 3.2.9 on 2022-02-06 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=32, verbose_name='Category')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_title', models.CharField(max_length=32, verbose_name='Department')),
                ('departament_description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('surname', models.CharField(max_length=32, verbose_name='Surname')),
                ('owner_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('departament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.departament')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('inventory_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('serial_number', models.CharField(max_length=128, verbose_name='S/N')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('date_purchase', models.DateField(blank=True, null=True, verbose_name='Date of purchase')),
                ('date_update', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Update')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.owner')),
            ],
        ),
    ]
