# Generated by Django 3.2.8 on 2021-11-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='department',
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(default=1, max_length=128, verbose_name='S/N'),
            preserve_default=False,
        ),
    ]
