# Generated by Django 3.2.8 on 2021-11-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211103_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='department',
            new_name='departament',
        ),
    ]
