# Generated by Django 3.2.8 on 2021-11-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_department_owner_departament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='department_description',
            new_name='departament_description',
        ),
        migrations.RenameField(
            model_name='departament',
            old_name='department_title',
            new_name='departament_title',
        ),
    ]
