# Generated by Django 3.2.8 on 2021-11-05 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211104_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_update',
            field=models.DateField(default=datetime.date(2021, 11, 5), verbose_name='Update'),
        ),
    ]
