# Generated by Django 3.2.8 on 2021-11-05 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211105_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_update',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Update'),
        ),
    ]
