# Generated by Django 3.2.8 on 2021-11-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_update',
            field=models.DateField(default=datetime.date.today, verbose_name='Update'),
        ),
    ]
